name: Secure-CI
on:
  pull_request:
    branches: [ "main", "staging" ]

jobs:     
  trivy_scan_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Perform Trivy scan for the OWASP Juice image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: bkimminich/juice-shop
          format: table
        
  trivy_scan_secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run trivy fs scan for secrets in the repository
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          security-checks: secret
          format: table
          exit-code: 1
          
  
  build_container:
    runs-on: ubuntu-latest
    needs: ["trivy_scan_docker_image", "trivy_scan_secrets"]
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker container from Docker Compose
        run: docker compose up --build -d
        
      - name: Run OWASP ZAP base scan
        uses:  zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:80'
          format: table

