name: Secure-CI
on:
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker container from Docker Compose
        run: docker compose up --build -d

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.64.1/trivy_0.64.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.64.1_Linux-64bit.deb
          
      - name: Perform Trivy scan for the owasp juice image
        run: trivy i bkimminich/juice-shop
          
